config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update] do
    collection do
      get :search
    end
  end
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  namespace :api do
    resources :messages, only: :index, defaults: { format: 'json'}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true

  def show_latest_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています。'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, through: :group_users
  has_many :messages
  has_many :group_users
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

  def index
    respond_to do |format|
      format.json { @messages = Message.where('id > ?', params[:id]) }
      format.html
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = current_user.groups.order("created_at DESC")
    @messages
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      first_join = current_user.group_users.new(group_id: @group.id)
      first_join.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
    def group_params
      params.require(:group).permit(:name, { :user_ids => [] })
    end

    def set_group
      @group = Group.find(params[:id])
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to "group_messages_path(params[:group_id])" }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private
    def message_params
      params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
    end

    def set_group
      @group = Group.find(params[:group_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = '更新しました'
      redirect_to root_path
    else
      flash[:danger] = '更新できませんでした'
      render :edit
    end
  end

  def search
    @users = User.where('name LIKE(?)', "%#{params[:group_users]}%").where.not('id = ?', current_user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :name )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
	- if @group.errors.any?
		.chat-group-form__errors
			%h2 = "#{@group.errors.full_message.count}件のエラーが発生しました。"
			%ul
				- @group.errors.full_messages.each do |message|
					%li = message
	.chat-group-form__field
		.chat-group-form__field--left
			= f.label :name, class: 'chat-group-form__label'
		.chat-group-form__field--right
			= f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
	.chat-group-form__field.clearfix

	.chat-group-form__field.clearfix
		.chat-group-form__field--left
			= f.label :'チャットメンバーを追加', class: "chat-group-form__label"

		.chat-group-form__field--right
			.chat-group-form__search.clearfix
				%input.chat-group-form__input#user-search-field{ placeholder: "追加したいユーザ名を入力してください", type: 'text', value: ""}
			#user-search-result
	
	.chat-group-form__field.clearfix
		.chat-group-form__field--left
			= f.label :'チャットメンバー', class: "chat-group-form__label"
		.chat-group-form__field--right
			#chat-group-users

	.chat-group-form__field.clearfix
		.chat-group-form__field--left
		.chat-group-form__field--right
			=f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'groups/form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
	= render partial: 'shared/side_bar', locals: { group: @group, user: @user}

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'groups/form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
	- flash.each do |key, value|
		= content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.messages__message(data-message-id='#{message.id}')
	.messages__message__upper-info
		%p.messages__message__upper-info__user
			= message.user.name
		%p.messages__message__upper-info__data
			= message.created_at.strftime("%Y/%m/%d %H:%M")
	%p.messages__message__text
		- if message.content.present?
			= message.content
		= image_tag message.image.url, class: 'message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper
  =render 'shared/side_bar'
  .chat-main
    .chat-main__main-header
      .chat-main__main-header__current-group
        %h2.chat-main__main-header__current-group__name
          = @group.name
        %ul.chat-main__main-header__current-group__member-list
          Member：
          %li.chat-main__main-header__current-group__member-list__member
            - @group.group_users.each do |group_user|
              = group_user.user.name
      = link_to edit_group_path(params[:group_id]), method: :get do
        .chat-main__main-header__edit-btn Edit
    .messages
      = render @messages
    .form
      = form_for([@group, @message], id: 'new_message')  do |f|
        .form__new-message
          .form__new-message__input-box
            = f.text_field :content, class: 'form__new-message__input-box__text', placeholder: "type a message"
            = f.label :image, class: "form__new-message__input-box__image-label" do
              = fa_icon "image", class: "form__new-message__input-box__image-icon fa"
              = f.file_field :image, class: "form__new-message__input-box__image-hidden"
          = f.submit 'Send',class: "form__new-message__submit-btn"
          

app/views/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name), class: 'btn'
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name), class: 'btn'
  %br/

app/views/shared/_side_bar.html.haml
.chat-side
	.chat-side__side-header
		%h3.chat-side__side-header__user-name
			= current_user.name
		%ul.chat-side__side-header__user-menu
			%li.chat-side__side-header__user-menu__edit-user
				= link_to new_group_path do
					%i.fa.fa-edit
			%li.chat-side__side-header__user-menu__new-group
				= link_to edit_user_path(current_user) do
					%i.fa.fa-cog
	.groups
		.groups__group
			- current_user.groups.each do |group|
				= link_to group_messages_path(group) do
					.groups__group__group-name
						= group.name
					.groups__group__latest-message
						= group.show_latest_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'